language: python
python:
 - "3.6"
sudo: false
cache:
  directories:
   - $HOME/.cache/pip
install:
 - pip install -q -rrequirements/base.txt
 - pip install -q -rrequirements/tests.txt
 - pip install coveralls
script:
 - py.test --cov-report= --cov=xlsxlite xlsxlite
 - flake8
after_success:
 - coveralls