name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    strategy:
      matrix:
        python-version: ['3.12.x', '3.13.x', '3.14.x']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Initialize environment
      run: |
        uv sync --group dev

    - name: Run ruff
      run: |
        uv run ruff format --check xlsxlite/
        uv run ruff check xlsxlite/

    - name: Run tests
      run: |
        uv run pytest --cov-report=xml --cov=xlsxlite xlsxlite

    - name: Upload coverage
      if: success() && env.CODECOV_TOKEN != ''
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        token: ${{ env.CODECOV_TOKEN }}
        fail_ci_if_error: true

  release:
    name: Release
    needs: [ test ]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.x'

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Publish release
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          uv build
          uv publish


  test-all:
    name: Test
    needs: [test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check all matrix legs passed
        run: test "${{ needs.test.result }}" = "success"
